src/components/Stack/Stack.tsx
This is messing with the proper margins for:
```tsx
<Stack type={StackType.cards}>
<Card>
<List>
<ListItem />
...
</List>
</Card>
</Stack>
```
=> Only apply last-child margins to modified children

package.json, src/components/Button/Button.tsx, src/index.ts, src/utils/AminoOnClickHandler.ts
This PR clarifies the onClick event type from the Button. Inferring the type was only showing AminoClickHandler instead of showing the actual type.
=> fix(button): clarify onclick type

package.json, src/components/Button/Button.tsx, src/components/DarkModeWrapper/DarkModeWrapper.tsx, src/components/DarkModeWrapper/index.ts, src/components/Dialog/Dialog.tsx, src/components/Layout/Layout.tsx, src/components/Select/Select.tsx, src/components/Tabs/Tabs.tsx, src/index.ts, src/primitives/Surface.tsx, src/styles/amino.css, src/styles/theme.css
First part of actual dark mode support! Let me know thoughts on this implementation of a wrapper component that forces specific sections to dark mode as well. Dark mode currently only applies to specific elements with the `data-theme="dark"` property, not following system behavior. So merging won't break anything since we aren't ready to deploy full dark mode any time soon. Additionally, I will send a follow up PR to remove references to `AminoTheme.ts`
Pic of `<DarkModeWrapper />` in action:
Video of full dark mode in action:
https://user-images.githubusercontent.com/926065/110404003-51478700-803b-11eb-8429-64f23055145a.mov
=> Add dark wrapper

.storybook/main.js, package.json, src/components/Select/Select.tsx, src/components/Stack/HStack.ts, src/components/Stack/index.ts, src/index.ts, src/stories/Button.stories.tsx, src/stories/Card.stories.tsx, src/stories/Checkbox.stories.tsx, src/stories/Combobox.stories.tsx, src/stories/DarkModeWrapper.stories.tsx, src/stories/Input.stories.tsx, src/stories/MenuButton.stories.tsx, src/stories/Notice.stories.tsx, src/stories/Radio.stories.tsx, src/stories/Select.stories.tsx, src/stories/Skeleton.stories.tsx, src/stories/Spinner.stories.tsx, src/stories/Stack/HStack.stories.tsx, src/stories/Tabs.stories.tsx
This PR fixes a problem with HStack inferred auto columns. The fix was found at css-tricks https://css-tricks.com/equal-width-columns-in-css-grid-are-kinda-weird/
This PR also avoids type-casting in the stories.
=> fix(hstack): inferred columns

package.json, src/components/Skeleton/Skeleton.tsx, src/stories/Skeleton.stories.tsx
@goodpickle I think you'll find this implementation of a shimmer effect for our skeleton loaders using styled components
(added animations based on suggestion from here: https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a - UX research shows that using a pulse animation improves the perception of speed that users have)
=> Fancier skeleton

package.json, src/components/AlertDialog/AlertContext.tsx, src/components/AlertDialog/AlertDialog.tsx, src/components/AlertDialog/index.ts, src/hooks/index.ts, src/hooks/useAlert.ts, src/index.ts, src/stories/AlertDialog/AlertConsumer.tsx, src/stories/AlertDialog/AlertDialogProvider.stories.tsx, src/types/AlertDialogOpts.ts, src/types/index.ts
Adds `<AlertDialog/>` and `useAlert` hook for easy access.
See example here: https://amino-ui-git-feat-alert-dialog-zonos.vercel.app/?path=/story/amino-alertcontextprovider--default-alert
Additionally cleans up the export of Amino's provided hooks.
=> Add Alert dialog

package.json, src/components/Card/Card.tsx, src/stories/Card.stories.tsx
This PR adds a card footer height to help cards in HStacks line-up better:
=> feat(card): add footer height

package.json, src/components/Card/Card.tsx
This PR makes the card children stretch instead of moving the footer around. It should fix:
=> fix(card): make children stretch

package.json, src/components/Text/Text.tsx, src/components/Text/index.ts, src/stories/Text.stories.tsx
N/A
This PR adds a ```title``` prop/attribute to the ```Text``` component to allow for accessibility even when instances of ```Text``` are truncated due to length.
=> feat(text): add title prop, story for Text

package.json, src/components/Layout/Layout.tsx
This is it...this is the one. The root error of all my styling woes turned out to be ```Content-Grid``` being set to 100% height. It's parent is ```Amino-Layout``` which is set to 100vh; thus we have situations where with a header there would be overflow for the content underneath the header. 
I have fixed and refactored the Layout component to be simpler, nuking the ```heightCss``` variable and moved it into the one place where it should matter, and set heights of all the children within ```ContentGrid``` to 100%. This should definitely help in the future when working with the header + sidebar + content areas and imo simplifies the the code while retaining functionality. 
Thanks for your patience.
=> fix(layout): switch from vh to % for children, fix contentgrid height error

package.json, src/components/Checkbox/Checkbox.tsx, src/icons/CheckIcon.tsx, src/icons/IconBase.tsx
This PR removes an extra/unnecessary click handler, and adds React refs to the ```CheckIcon``` component and its children in order to eliminate an error during its use as a custom ```motion``` component.
=> fix(checkbox): remove extra onClick, add forwardRefs

package.json, src/components/Slider/Slider.tsx
N/A
This PR changes the position of the the Indicator to relative, as setting it to absolute was causing some height calculation problems in Dashboard and as I want to avoid hard-coded heights, changed the Indicator position to relative to place the Indicator back into the document flow. 
Setting the position to relative should place the Indicator back into the document flow and have it be factored into height calculations and avoid unnecessary overflow for this and other cases.
=> fix(slider): change position of indicator

package.json, src/components/RichRadio/RichRadio.tsx, src/stories/RadioGroup.stories.tsx, src/stories/RichCheckbox.stories.tsx, src/stories/RichRadio.stories.tsx
This PR fixes Rich Radio visual jankiness if the label was long enough to interfere with the checkmark. This PR removes the default value which makes the Rich Radio a controlled component.
This PR fixes a typescript issue inside the Storybook.
=> Fix Rich Radio visual jankiness for long labels

src/components/Select/CountryMultiSelect.tsx, src/components/Select/MultiSelect.tsx, src/components/Select/StyledReactSelect.tsx, src/stories/Select.stories.tsx
[Amino 3 - Country select](https://myzonos.atlassian.net/browse/BBT-515?focusedCommentId=55686)
This PR fixes the select label design to have the selected item blue for single selects with a checkmark to the far right. In addition to defaulting to not showing the option in the list for multi-select.
=> feat(select): fix label design

build-utils/build.ts, src/stories/CountrySelect/CountryMultiSelect.stories.tsx, src/stories/CountrySelect/CountrySelect.stories.tsx
This PR allows rollup to be able to bundle both default export and named export
=> refactor: change named export to default

build-utils/css/constants/theme.ts, build-utils/css/utils/__snapshots__/theme.css, build-utils/css/utils/__tests__/__snapshots__/convertToCssVariable.test.ts.snap, build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap, src/components/toast/Toast.tsx, src/components/toast/ToastContext.tsx, src/stories/Toast/Toast.stories.tsx, src/stories/Toast/ToastConsumer.tsx, src/styles/amino.css, src/styles/constants/theme.ts, src/styles/theme.css
[FE: Add category and subcategory selection (final step) to Classify Interactive in dashboard UI](https://myzonos.atlassian.net/jira/software/projects/CLSFY/boards/65?assignee=603058259f84a900690cdd2b&selectedIssue=CLSFY-1512)
This PR adds the Figma design for Toast notifications and added intent for different options. 'Success' toast needed for Classify figma design.
=> feat(toast):added intent/options to Toast

package.json, src/components/toast/ToastContext.tsx
Fixes toasts not setting unique key properly. Previously was setting to `Date.now()` inside the map function call, which changed on each render. Now we are using `uuid` to set it to guarantee uniqueness.
=> fix(toast): give actual unique keys

package.json, src/components/help-text/HelpText.tsx, src/components/input/input-type/_FloatLabelInput.tsx, src/stories/Input.stories.tsx, src/stories/Select.stories.tsx
The `error` and `helpText` props for Inputs were very confusing in their functionality.
I changed it to make `error` a boolean for an error state, and `helperText` be whatever text is shown below, error or otherwise. See the new input story for a demo.
Upstream users will have invalid `error` prop types, but most of those can probably be fixed by making the previous error value evaluate the falsiness, as most cases look like this:
```tsx
<Input
helpText={renderIossHelpText()}
error={renderIossHelpText()}
label="IOSS VAT number"
onChange={({ target: { value } }) => setIossNumber(value)}
value={iossNumber || ''}
/>
```
=> feat: make helptext and error be more sensible types and update stories.

package.json, src/components/input/input-type/_DateInput.tsx, src/stories/Input.stories.tsx
Given a `min` and `max` for a date input, it will render a native placeholder, which interfered with our label. This fixes that (thanks @Thienhuynh95 for the fix)
Old:
The new one just hides that placeholder until we focus.
=> fix: native datetime placeholder is hidden correctly now

package.json, src/components/stack/Stack.tsx, tsconfig.json, yarn.lock
There was an issue when I updated the docs to use the latest version of Amino. The Vstack typescript no longer allowed a tabIndex prop. This PR adds typing to allow that to happen.
=> FIX: Allow div props on vstack

src/components/text-avatar/TextAvatar.tsx, src/stories/TextAvatar.stories.tsx
When trying to fix the store switcher in dashboard I ran into a serious scrolling performance issue. To make a (really) long story short, the issue was actually the styled component `TextAvatar` it was rendering. styled-components gave me a warning in the console for generating over 200 classes and a slightly cryptic fix.
TLDR: CSS class generation is computationally expensive, especially in large lists. Inline styles are quick. 
Also made the TextAvatar story more ... colorful 😄 
Console warning in question:
```
instrument.js?b344:107 Over 200 classes were generated for component styled.div with the id of "sc-jGprRt".
Consider using the attrs method, together with a style object for frequently changed styles.
Example:
const Component = styled.div.attrs(props => ({
style: {
background: …
```
=> fix: TextAvatar inline styling

package.json, yarn.lock
This PR fixes a Nextjs build error by reverting the `d3-geo` package down to 2.0.2 which is before `d3-geo` started compiling down to using the `import` syntax instead of the `require` syntax.
```
require() of /vercel/path0/node_modules/d3-geo/src/index.js from /vercel/path0/node_modules/@amino-ui/core/components/connection-map/ConnectionMap.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
```
=> fix: revert d3-geo to pre type:module version

package.json, src/components/alert-dialog/AlertDialog.tsx, src/components/dialog/Dialog.tsx, src/components/dialog/_BaseDialog.tsx, src/stories/Dialog.stories.tsx
Adds pressing `escape` or clicking outside of dialog for options to close it. Default to true and won't do aything if `onClose` is undefined.
Also fixes some styling on the Dialog to match the figma design (except the close icon, which just looks way too small in the design, and we were using it bigger anyways)
=> feat: add esc and click out of dialog actions to close.

build-utils/css/README.md, build-utils/css/class/LogicConstant.ts, build-utils/css/class/__tests__/LogicConstant.test.ts, build-utils/css/class/__tests__/__snapshots__/LogicConstant.test.ts.snap, build-utils/css/class/template/logicConstant.tpl, build-utils/css/generateLogicConstTemplate.ts, package.json
This PR:
- Added a new script to generate a template by just running the command `yarn template:logic-constant fileName`  (make the process easier instead of having to do extra work like copy and paste (like copy and edit the previous file constant, edit file name/file content manually and file content syntax may become inconsistent)
- Added unit tests for the generating template process
=> feat: generating logic constant template

package.json, src/components/table/TableRow.tsx, src/components/table/TableRowCollapse.tsx, src/stories/Table.stories.tsx
This PR allows expanding the Expandable Table Row when there are children. In addition, the click event is now on the table row instead of the button.
=> feat(table-row): allow expand with children

package.json
Accidentally broke the build script, and it didn't try and run it because it wasn't a tag, and then failed on the next one.
=> build: fix build script

package.json, src/components/dialog/_BaseDialog.tsx, src/stories/Dialog.stories.tsx
Fixes an issue I introduced when adding click outside dismissing for dialogs. Clicking links wouldn't work, probably among other things as well.
=> fix: dialog click events being cancelled

.github/workflows/publish.yml
Didn't like staring at the Publish action waiting for it to finish, so maybe caching dependencies will make it faster.
=> build(actions): update publish actions

package.json, src/components/collapse/Collapse.tsx, src/stories/Collapse/Collapse.stories.tsx, src/utils/useResizeAware.tsx
Fixes an issue with the `Collapse` component where `overflow: hidden` was causing box shadows (and anything outside the components bounding box) to be hidden.
Also made the Collapse story slightly nicer.
=> fix: overflow auto when fully expanded

package.json, src/components/select/CountryMultiSelect.tsx, src/components/select/CountrySelect.tsx, src/components/select/__stories__/CountryMultiSelect.stories.tsx, src/components/select/__stories__/CountrySelect.stories.tsx, src/types/ICountry.ts, src/utils/prepRegionCountryOptions.ts
This PR:
- Improve `CountrySelect` and `CountryMultiSelect` to provide more strongly typed data.
**Ex**: If some strongly typed `RandomCountryCode` variables are passed in `countryOptions`, `onChange` and `value` should give the correct type based on the `countryOptions` variables, which is `RandomCountryCode` and not just primitive `string` type.
=> refactor: strongly type for countryselect

package.json, src/components/tooltip/Tooltip.tsx, src/components/tooltip/__stories__/Tooltip.stories.tsx
Storybook url:
- [Tooltip w orange background](https://amino-b9bba0mop-zonos.vercel.app/?path=/story/amino-tooltip--default&args=background:orange400)
This PR:
- add `open` prop to easily manipulate the open state
- custom `background` to the tooltip
=> style(tooltip): add custom background & open prop

package.json, src/components/collapse/Collapse.tsx, src/components/collapse/__stories__/Collapse.stories.tsx
[MdxCollapse animates open instead of just being open right on page load](https://myzonos.atlassian.net/browse/DOCS-292)
This PR fixes an issue where the Collapse would animate the initial state if it started open. I also made it `opacity:0` because if it ever had borders and such it would still show while collapsed.
=> fix: collapse initial state animation and add to story to show

package.json, src/components/drop-zone/DropZone.tsx, src/components/input/input-type/_DateInput.tsx, src/components/input/input-type/_NumberInput.tsx, src/components/input/input-type/_PasswordInput.tsx, src/components/input/input-type/_TimeInput.tsx, src/components/layout/__stories__/UserMenu.tsx, src/components/rich-checkbox/RichCheckbox.tsx, src/components/rich-radio/RichRadio.tsx, src/components/tag/Tag.tsx
I noticed in account-web that clicking the hide password eye icon causes the submit event to fire, which is because default button type is `submit`.
This PR adds `type="button"` to all our buttons so this does not happen.
=> fix: add button type 'button' everywhere

package.json, src/components/collapse/Collapse.tsx
This PR removes the `useLayoutEffect` from Collapse. It originally was needed with the old design, but now it looks like it isn't needed anymore. It was breaking the SSR, so this ends up working out nicely.
=> refactor: remove layout effect

package.json, src/components/slider/Slider.tsx, src/components/slider/__stories__/Slider.stories.tsx
Preview url: [link](https://amino-mp0d7lg6y-zonos.vercel.app/?path=/story/amino-slider--slider)
This PR:
- remove fixed height when hiding indicator
- add size props for the thickness of the bar
- make it transition smoother when the value is set directly
=> refactor(slide): smoother when suddenly slide

src/components/button/Button.tsx, src/components/connection-map/__stories__/ConnectionMap.stories.tsx
[Avoid Uppercase Acronyms](https://myzonos.atlassian.net/browse/FE-15)
This PR converts some uppercase acronyms to camelCase.
Patterns: `SWRT`,  `HTML`, `SWR`, `QL`, `HTTP`, `HTTPS`, `AI`, `AST`, `API`, `JSON`.
This updated with Vscode:
**PS:** There would be some cases that are not what we want. You would need to filter and commit only the changes you want: 
VsCode search setting 
- Search input: `([a-z])(SWRT|HTML|SWR|QL|HTTP|HTTPS|AI|AST|API|JSON)`
- Replacement: `$1\u\L$2`
- Files to exclude: `*.json`
=> refactor: convert camelCase for acronyms

package.json, src/components/button/Button.tsx, src/components/connection-map/ConnectionMap.tsx, src/components/connection-map/__stories__/ConnectionMap.stories.tsx, src/components/currency/Currency.tsx
This PR changes:
- text button type doesn't have a ripple anymore (noticed in dashboard back button)
- currencies use number formatting currency style to get better i18n (wanted 2 significant digits always, and found a better option)
- connection map loading state is better
=> Fix: text button ripple, currency formatting

package.json, src/components/cover-sheet/CoverSheet.tsx, src/components/cover-sheet/CoverSheetActions.tsx, src/components/cover-sheet/__stories__/CoverSheet.stories.tsx
- CoverSheetAction is set to attach to an id of a `CoverSheet` wrapper that doesn't exist, so in case of the `Create Label` in the `Create Label flow` in the dashboard disappears, and it's hard to narrow down why as nothing in the dev tool console.
This PR shows the errors in the console when couldn't find the id to attach to in the whole Dom
=> refactor(CoverSheet): show error when id not found

package.json, src/components/lightbox/LightBox.tsx
This PR removes the forwardRef from the lightbox. The forwardRef was causing a warning in Docs that was not showing on Amino.
=> Fix(lightbox): Fixed forward ref issue

package.json, src/components/textarea/Textarea.tsx, src/components/textarea/__stories__/Textarea.stories.tsx
- `Textarea` component when no label specified, the cursor will not appear even when the component is focus
This PR fixes the issue by showing the label cover only when there is a `label` prop in `Textarea` component.
=> fix: text area cursor got covered by the label placeholder when has no label

package.json, src/components/announcement-dialog/AnnouncementDialog.tsx, src/components/announcement-dialog/__stories__/AnnouncementDialog.stories.tsx
This PR makes some unnecessary required props become optional. I also removed the type from the announcement label because I've already seen 3 different instances and there will be more to come. There is now a label and title prop.
=> Fix(theme): Announcement component fixed

package.json, src/components/cover-sheet/CoverSheet.tsx, src/components/dialog/_BaseDialog.tsx
[Dialog backdrop position](https://myzonos.atlassian.net/jira/software/projects/FE/boards/145?selectedIssue=FE-273)
[Theme bug fixes](https://myzonos.atlassian.net/jira/software/projects/FE/boards/145?selectedIssue=FE-270)
This PR brings back the react portal to the dialog and coversheet components. To get the data-theme to apply, we are using the useAminoTheme hook to get the theme if there is no `themeOverride` present. Scrolling is also disabled when the dialog or coversheet is open.
=> Fix (theme): Dialog and Coversheet revert to use createPortal

.storybook/buildStories.ts, .storybook/main.ts, package.json, src/components/theme-select/__stories__/ThemeSelect.stories.mdx, src/components/theme-select/__stories__/ThemeSelect.stories.tsx, src/utils/hooks/useAminoTheme.ts
This PR adds a doc story for theme usage.
~No version bump as these are internal story only changes.~ Hook has an added optional prop to modify the root.
Link: https://amino-git-feat-theme-usage-docs-zonos.vercel.app/?path=/docs/amino-themeselect-usage--docs
I went back and forth on the doc (mdx) story loading, but I figured it would be too specific and rare to have custom logic for finding those stories. As a result, if you want to add a doc story, then you will have to manually set the title.
=> stories: mdx doc stories for theme usage

src/components/graph-matrix/GraphMatrix.tsx
[FE-221 - Amino: GraphMatrix - Graphiql cursor jump when typing fast](https://myzonos.atlassian.net/browse/FE-221)
This PR implements a workaround to prevent the cursor from jumping to the beginning of the query window when typing quickly
this fix comes from:
https://github.com/graphql/graphiql/issues/2368#issuecomment-1176119332 possibly doesn't work all the time, GitHub issue is not being worked on as GraphiQL is looking to reimplement the Explorer plugin soon
=> fix(GraphMatrix): workaround for cursor jumping

package.json, src/components/collapse/Collapse.tsx, src/components/collapse/__stories__/Collapse.stories.tsx
Collapse doesn't detect when content height change which leads to part of item cut off in label creation.
This PR adds resizeObserver to detect height change and a story for the fix (when open the story, it will add 2 more items to the list after 2 seconds, and those 2 will be removed after 2 seconds later), you can also add more items manually.
https://amino-ov78kk3t6-zonos.vercel.app/?path=/story/amino-collapse--collapse
`ResizeObserver` browser compatibility looks really good:
=> refactor: update size when content change

licenses/README.md, licenses/license-dnd-kit.md, licenses/license-mui.md, licenses/license-react-select.md, package.json, src/components/collapse/Collapse.tsx, src/components/collapse/__stories__/Collapse.stories.tsx
This PR swaps out the Collapse implementation with material-ui's Collapse because theirs is 🔥 . Tweaked the Collapse stories to more accurately reflect our use cases.
Originally needed fixing because it did not behave well when nested.
Adds some licenses as an afterthought.
=> feat: use mui collapse for collapse

package.json, pnpm-lock.yaml, src/components/switch/Switch.tsx, src/components/switch/__stories__/Switch.stories.tsx, src/components/theme-select/ThemeSelect.tsx
This PR brings over the switch we have with icons nested in the switch. I already made the replacement in Amino for the theme switch toggle on zonos.com/docs and will be used for the new mobile/desktop view in dashboard.
=> FEAT: Switch with icons

package.json, src/components/dialog/BaseDialog.module.scss
This pull request adds a max-height property to the dialog popup component, ensuring that it does not exceed 90% of the viewport height.
=> Add max-height to dialog popup

package.json, src/components/glow/GlowWrapper.module.scss, src/components/input/__stories__/Input.stories.tsx, src/components/input/input-type/_FloatLabelInput.module.scss, src/components/layout/Layout.module.scss, src/components/textarea/Textarea.tsx
Input placeholder overlap
- Access this link: https://amino-git-fix-pseudo-element-prefix-zonos.vercel.app/?path=%2Fstory%2Famino-input--number-input. The second input of each `Input` story is the one with `placeholder`. `placeholder` will be hidden when there is nothing on it, click on it the placeholder should show up.
This PR add prefix `&` to all pseudo selectors `::`
=> refactor: add prefix to all pseudo elements

package.json, src/components/simple-table/SimpleTable.tsx
[Add the ability to see the translations to the custom message settings](https://myzonos.atlassian.net/browse/FE-828)
This PR allows customizing the table header with `noPadding` and passing in a React Node for the header name. This should allow proper formatting for the Translated messages dialog in Dashboard.
=> feat(simple-table): customize th

package.json, src/components/input/Input.tsx, src/components/select/_StyledReactSelect.module.scss
Related to [FE-810 - Dashboard to css modules](https://myzonos.atlassian.net/browse/FE-810)
This PR fixes some small bugs from the css module conversion:
- fix medium `_StyledReactSelect` top value from `hasLabel` to `hasValue`
- pass `className` to default `Input` component
=> fix: small bugs from css modules conversion

package.json, src/components/input/Input.tsx
This PR fixes a mistake from the previous version.
I misunderstood what I was looking at in the Input component. The previous "fix" ends up passing the classname twice, which explodes in the input when it is styled.
=> fix: undo class passing to input

package.json, src/components/cover-sheet/CoverSheet.tsx, src/components/cover-sheet/__stories__/CoverSheet.stories.tsx
[Implement iframe for Screen calculator UI](https://linear.app/zonos/issue/TS-530/implement-iframe-for-screen-calculator-ui)
This PR makes the close button optional. This will allow us to use Coversheets without a close button in iframes.
=> feat(coversheet): make close button optional

package.json, src/components/layout/Layout.module.scss
This PR removes the strict height on the amino Layout footer. Not sure why it was necessary in the first place? 🤔
I'm adding a new piece to the dashboard sidebar footer and this is what I need done.
=> fix(layout): auto sidebar footer height

package.json, src/components/thumbnail/Thumbnail.tsx, src/components/thumbnail/__stories__/Thumbnail.stories.tsx
This PR adds color overrides to Thumbnails when we don't want to use the default color schemes for thumbnails.
PREVIEW
<https://vercel.live/open-feedback/amino-git-fix-thumbnail-zonos.vercel.app?via=pr-comment-visit-preview-link&passThrough=1>
1. Open thumbnail
2. Choose a duotone icon
3. Select override colors for both
=> Fix(thumbnail): add color override props

package.json, src/components/avatar/AvatarBase.tsx
[FE-870 : Update Avatar `rounded` border radius](https://linear.app/zonos/issue/FE-870/update-avatar-rounded-border-radius)
This is being used in the gql-fulfillment branch of Dashboard.
Design wants the border-radius for the Avater components to be different based on the size of the component I was able to calculate the sizes they want into an equation.
This PR updates the border radius for the BaseAvatar
=> fix: change the Avater rounded border radius

build-utils/css/constants/theme/night/_shadow.ts, build-utils/css/utils/__tests__/__previous-test-files__/night-theme.css, build-utils/css/utils/__tests__/__snapshots__/generateCSS.test.ts.snap, package.json, src/components/badge/Badge.module.scss, src/components/dialog/BaseDialog.module.scss, src/components/filter/FilterWrapper.module.scss, src/components/slide-over/SlideOver.module.scss, src/styles/theme.css
Adjusts "raised" elements that contain buttons to stay the page background color instead of a lighter surface color.
Adjusts dark mode shadows to have a lighter border to contrast from the background
Fixes gray badge not getting last update.
=> adjust dark mode shadows and raised elements

package.json, src/components/dialog/DismissableDialog.module.scss, src/components/dialog/alert/AlertDialog.tsx, src/components/dialog/alert/__stories__/AlertConsumer.tsx, src/components/dialog/confirm/__stories__/ConfirmConsumer.tsx, src/utils/storage.ts
This PR fixes an issue with the storage lifetime util where it was formatting the data only to the day, preventing any finer time ranges.
Also makes dismissable dialogs actions width consistent.
Also apparently `dismissable` is not a real word and it is is `dismissible`... but the truth is whatever we make it.
=> fix: storage lifetime allow more granularity

src/components/filter/filter-amount/FilterAmount.tsx
This PR fixes a bug on current amino.zonos.com. When filtering a number with a zero after the decimal, it removes the zero immediately because it's reducing the number to simplest state. With a string, it allows it to use zeros.
See preview link for fix
=> fix(amountFilter): use string instead of number for input state

package.json, src/components/textarea/Textarea.module.scss, src/components/textarea/Textarea.module.scss.d.ts, src/components/textarea/Textarea.tsx, src/components/textarea/__stories__/Textarea.stories.tsx, src/utils/hooks/useHeightAdjustTextarea.ts
This PR adds the ability for a text area to accept actions. The actions are positioned absolute in the bottom right corner of the textarea. For textarea where we expect larger text entries, it should be made `expandable` and have a greater `maxRows` count so it has a nice auto increase rather than the text getting cut off above the buttons. (I left this up to developer implementation)
https://amino-git-feat-textarea-actions-zonos.vercel.app/?path=%2Fstory%2Famino-textarea--with-actions&args=maxRows%3A15%3Bexpandable%3A%21true
=> Feat: Textarea actions

package.json, src/components/button/Button.module.scss, src/components/button/Button.module.scss.d.ts, src/components/button/Button.tsx, src/components/button/__stories__/Button.stories.tsx, src/types/Variant.ts
This PR adds a new button variant of `Inverted` which basically inverts the default button by changing the theme with a fixed `gray0` background color. It also fixes the `themeOverride` prop as it wasn't working properly on the story.
=> feat(invertedButton): Inverted button variant and fix theme override

package.json, src/components/button/Button.module.scss, src/components/button/Button.tsx, src/components/spinner/Spinner.module.scss, src/components/spinner/Spinner.module.scss.d.ts, src/components/spinner/Spinner.tsx
This PR officially fixes the button themes and variants. It also removes the use of the amino theme hook on the button and just uses CSS to transform the white spinners for the appropriate buttons. Screenshots of running zonos.com locally against the change.
I have learned that using the `useAminoTheme` hook within amino is something we should mostly steer away from because in instances like zonos.com we hard code the `data-theme` attribute to `night` which doesn't change what value `useAminoTheme` pulls from local storage.
=> Fix: Final button fix for themes and inverted variant

package.json, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/__stories__/SimpleTable.stories.tsx
https://linear.app/zonos/issue/ONB-667/frontend-add-copiable-order-numbers-in-order-search
This PR adds a prop to simple table headers that disables link clicks for that specific column. My use case is for the order list page. Product wants the `accountOrderNumber` to have a copy ability. But copying triggers the Iink.
PREVIEW: https://amino-git-fix-table-zonos.vercel.app/?path=%2Fstory%2Famino-simpletable--with-link
=> fix(table): add disabled link feature for certain columns

package.json, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/__stories__/SimpleTable.stories.tsx, src/utils/hooks/__tests__/useStorage.test.ts, src/utils/hooks/useStorage.ts
This PR:
- allows falsy storage values
- `SimpleTable` moves CSS props to wrapper (I understand dashboard styles it in a few places and I will verify those)
=> fix: falsy storage values

package.json, src/components/simple-table/SimpleTable.module.scss, src/components/simple-table/SimpleTable.module.scss.d.ts, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/__stories__/SimpleTable.stories.tsx
https://amino-git-fix-components-zonos.vercel.app/?path=/story/amino-simpletable--custom
1. Click the `Disable truncate` checkbox
2. Click the `View one row` checkbox and then click the menu to see it's no longer cut off. 
This PR makes table cells truncate by default with the option to to disable truncating by column. It will just truncate at the percentage width specified in the header columns.
It also removes `overflow: auto` from the table wrapper. I didn't see any repercussions, but maybe I missed something.
=> FIX: Simple table styling and truncate text

package.json, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/__stories__/SimpleTable.stories.tsx
This PR changes the min width to be in pixels rather than percentage. Now that we are more commonly truncating, percentage min width doesn't work. Min width in pixels will allow us to truncate up to a certain point so it's not too small.
PREVIEW:
=> FIX: Simple table min width in pixels

package.json, src/components/simple-table/SimpleTable.module.scss, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/__stories__/SimpleTable.stories.tsx
This PR restores width percentage to work in tandem with min width in pixels. Also adds alignment of the tooltip to not just be center all the time.
=> fix(simpleTable): use width percentage and min width in pixels together

package.json, src/components/simple-table/SimpleTable.tsx, src/components/tooltip/Tooltip.tsx
This PR sets table tooltip hover delays to 800 miliseconds. I want to get it to hide tooltips if the text isn't actually being truncated, but will attempt that at a future date since there's not an easy way to do that.
=> FIX: Simple table tooltip hover

package.json, src/components/button/Button.module.scss
This PR makes the `inlineLink` button inherit line height from the parent rather than the classic button line height. (32px down to 24px)
NOW: https://amino-git-fix-components-zonos.vercel.app/?path=/story/amino-button--inline-link-button-story&vercelToolbarCode=cZdcr2nqTdrXBZA
PREVIOUS: https://amino.zonos.com/?path=%2Fstory%2Famino-button--inline-link-button-story
=> FIX: Inline button link line height

package.json, src/components/input/input-type/_FloatLabelInput.module.scss
[TS-1545: Improve date input small size focus state](https://linear.app/zonos/issue/TS-1545/improve-date-input-small-size-focus-state)
Click on the second input
Before:
https://amino.zonos.com/?path=/story/amino-input--date-input&args=size:sm
After: 
https://amino-git-refactor-improve-date-input-sm-size-zonos.vercel.app/?path=/story/amino-input--date-input&args=size:sm
Resolved TS-1545
This PR fixes css for small input on focus state
=> refactor: improve input date type sm size

.github/workflows/playwright.yml, .gitignore, package.json, src/components/flex/Flex.tsx, src/components/toast/Toast.module.scss, src/components/toast/Toast.module.scss.d.ts, src/components/toast/Toast.tsx, src/components/toast/ToastContext.module.scss, src/components/toast/ToastContext.module.scss.d.ts, src/components/toast/ToastContext.tsx, src/components/toast/__stories__/ToastConsumer.tsx, src/styles/amino.css
https://amino-git-fix-components-zonos.vercel.app/?path=%2Fdocs%2Famino-toast--docs&vercelToolbarCode=Gl4S6TvQK-wtTjA
Click to show persistent and non-persistent toasts to see how they work. Clear one at a time or clear all.
This PR adds a new type of persisting toasts that layer over the top of one another. In dashboard, we will make a proxy the `useNotify` hook to make all error notifications be persisting toasts for a subset of users to implement error support requests. The persistent toast stack can be cleared with a "clear all" button.
The regular toasts that do not persist, will stack on top and disappear as they have been.
=> FEAT: persisting toasts

package.json, src/components/button/Button.module.scss, src/components/button/Button.tsx, src/components/button/__stories__/Button.stories.tsx
This PR fixes an issue with the `linkButton` where we no longer were allowing a color override. I didn't see any other issues from the [PR](https://github.com/Zonos/amino/pull/728) that introduced the issue.
=> fix(button): link override color

package.json, src/components/toast/Toast.module.scss, src/components/toast/Toast.module.scss.d.ts, src/components/toast/Toast.tsx, src/components/toast/__stories__/ToastConsumer.tsx
This PR fixes the alignment for toasts one last time. Just set the dismiss icon to align to top. Everything else is centered.
https://amino-git-fix-components-zonos.vercel.app/?path=%2Fdocs%2Famino-toast--docs
To preview, click the different persistent toasts.
=> fix(toast): fix alignment for persisting toasts

package.json, src/components/toast/ToastContext.tsx, src/components/toast/__stories__/ToastConsumer.tsx
This PR exposes a new function from ToastContext to dismiss all toasts. Product wants to dismiss all toasts when a user clicks the request support button.
=> FEAT: Dismiss all toasts 

package.json, src/components/simple-table/SimpleTable.module.scss
This PR makes a small fix to lock the collapse chevron to the end of the row, rather than acting like a normal <td> element
=> fix: lock collapse button to end of row

package.json, src/components/simple-table/__stories__/SimpleTable.spec.ts, src/components/toast/ToastContext.module.scss, src/components/toast/ToastContext.tsx
This PR makes it so duplicate toasts can easily be stopped by passing an id. No duplicate IDs allowed.
This PR also:
* removes pointer events from the container and only allows them on the toasts wrappers (allows clicks behind the container)
* hides actions in addition to content when not the first toast
* fixes simple table test
* fixes a bug when a second toast with tall actions makes it taller than the first (hide the actions just like we were hiding the content)
=> FIX: Disallow duplicate toast ID's

build-utils/build.ts, package.json
This PR resolves an issue causing webpack to fail to compile the dynamic import. It ended up searching for the `.d.ts` files first.
```
./node_modules/.pnpm/@zonos+amino@5.5.1_@emotion+react@11.11.4_@emotion+styled@11.11.5_@types+react@18.3.12_dayjs@_bucgt74sijkpgdbgwbobd5v7h4/node_modules/@zonos/amino/icons/flags/AI.d.ts
Module parse failed: Unexpected token (2:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /// <reference types="react" />
> type Props = {
|     borderRadius?: number;
|     height: number;
Import trace for requested module:
./node_modules/.pnpm/@zonos+amino@5.5.1_@emotion+react@11.11.4_@emotion+styled@11.11.5_@types+react@18.3.12_dayjs@_bucgt74sijkpgdbgw …
```
=> fix: dynamic import look for JS file

package.json, src/components/checkbox/Checkbox.module.scss, src/components/checkbox/Checkbox.tsx, src/components/checkbox/__stories__/Checkbox.stories.tsx, src/components/select/_StyledReactSelect.tsx
[CXT-1344: Frontend - Fix checkbox in Amino](https://linear.app/zonos/issue/CXT-1344/frontend-fix-checkbox-in-amino)
This PR moves the subtitle out of the checkbox label element. It was causing nested links to be un-clickable and is actually recommended as a poor user experience by [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content). Removed unnecessary props because of this change.
Preview: https://cade.amino.zonos.com/?path=/story/amino-checkbox--checkbox-with-complex-subtitle
Country multiselect still works: https://cade.amino.zonos.com/?path=/story/amino-country-multi-select-countrymultiselectexpanded--basic
=> FIX: Checkbox label

package.json, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/__stories__/SimpleTable.stories.tsx
This PR makes checkboxes work without triggering a row click
Preview: https://amino-git-fix-components-zonos.vercel.app/?path=/story/amino-simpletable--selectable
Try first click on row and try first click on checkbox
=> Fix: Simple table row click with selectable table bug

package.json, src/all.ts, src/components/filter/FilterWrapper.module.scss, src/components/simple-table/SimpleTable.module.scss, src/components/simple-table/SimpleTable.module.scss.d.ts, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/SimpleTableRow.module.scss, src/components/simple-table/SimpleTableRow.module.scss.d.ts, src/components/simple-table/SimpleTableRow.tsx
https://amino-git-fix-components-zonos.vercel.app/?path=/story/amino-simpletable--basic
This PR moves table rows into a child component `SimpleTableRow`. This ref code previously violated React's Rules of Hooks by introducing a dynamic number of hook calls between renders because we were calling `useRef` directly in a mapped list. Creating the ref within a child component will fix this issue. This change makes the files a little easier to read as well. 
I ran these changes locally in dashboard and everything is looking good. All tests passing still.
This PR also:
- adds a higher z-index to filters so the dropdowns stop getting cut off by table headers.
- fixes some bugs noticed with truncating.
=> FIX: Simple table useRef bug

package.json, src/components/filter/filter-date/FilterDate.tsx, src/components/filter/filter-date/_DateControls/_IsBeforeOrOn.tsx, src/components/filter/filter-date/_DateControls/_IsBetween.tsx, src/components/filter/filter-date/_DateControls/_IsEqualTo.tsx, src/components/filter/filter-date/_DateControls/_IsOnOrAfter.tsx
This PR fixes a bug in the Date Filter where typing the date into the date inputs was incredibly buggy and difficult to use.
**Before**
<https://amino.zonos.com/?path=/story/amino-filters--date>
**After**
<https://nick.amino.zonos.com/?path=/story/amino-filters--date>
Functionality should be the same between the two versions, but typing the dates will be more intuitive in the **After**
=> fix: date filter input bugs

package.json, src/components/simple-table/SimpleTable.module.scss, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/SimpleTableRow.module.scss, src/components/simple-table/SimpleTableRow.module.scss.d.ts, src/components/simple-table/SimpleTableRow.tsx
This PR fixes the styling for simple table. A global table style accidentally slipped through giving the potential to break other tables. Corrected some other styling as well.
https://cade.amino.zonos.com/?path=/story/amino-simpletable--selectable
=> FIX: Simple table styling

package.json, src/components/simple-table/SimpleTable.module.scss, src/components/simple-table/SimpleTable.tsx, src/components/simple-table/__stories__/SimpleTable.spec.ts
This PR fixes the loading styles for the simple table after refactoring in a previous PR. It also writes a test for my previous PR against selecting rows and disabling the onClick event.
https://cade.amino.zonos.com/?path=/story/amino-simpletable--loading
=> FIX: Simple table loading state

package.json, playwright.config.ts, src/components/select/_StyledReactSelect.tsx, src/components/select/__stories__/Select.stories.tsx, src/components/simple-table/SimpleTableRow.module.scss, src/components/simple-table/__stories__/SimpleTable.spec.ts, src/components/simple-table/__stories__/SimpleTable.stories.tsx
This PR fixes the React Select to allow for passing a `styles` prop that actually merges with our base styles in amino. This PR also fixes the simple table for link rows so the whole thing is clickable and fixes links to truncate again. Created a story to see the text wrap methods working.
Link rows:
https://cade.amino.zonos.com/?path=/story/amino-simpletable--with-link
Text Wrap Method:
https://cade.amino.zonos.com/?path=/story/amino-simpletable--text-wrap-methods
Select with custom styles prop for background color:
https://cade.amino.zonos.com/?path=/story/amino-select--customized
Ran the built changes on dashboard and looks good ✅
=> FIX: Select styles and simple table links

package.json, src/components/input/input-type/_FloatLabelInput.module.scss
[SN-2198: Frontend - Floating Labels in Amino sometimes override the text that is entered](https://linear.app/zonos/issue/SN-2198/frontend-floating-labels-in-amino-sometimes-override-the-text-that-is)
This PR fixes the CSS for the XL FloatLabelInput. The floating styles weren't getting applied correctly upon `:focus-within` or `.has-content` until unfocused. Oddly, this only occurs outside of Amino's Storybook, in consuming projects.
Not sure how to add a preview. I tested by importing my local Amino into my local Zonos.com and this fix worked.
=> fix: input xl float label

package.json, src/components/filter/filter-date/FilterDate.tsx
[CXT-1523: Fix Date Filter in Amino](https://linear.app/zonos/issue/CXT-1523/fix-date-filter-in-amino)
This PR fixes a bug where the date being `null` causes the dayjs call to return 'Invalid date'. This fix makes the `getAdjustedDate` function return `null` if the date is `null`.
=> fix: if date is null, don't run dayjs on it.

package.json, src/icons/flag-icon/FlagIcon.tsx
This PR reverts the FlagIcon implementation to its previous version. The current lazy/Suspense implementation is causing flickering and rendering loops in Dashboard
=> fix: reset FlagIcon to previous implementation

package.json, src/components/toggle/Toggle.module.scss, src/components/toggle/Toggle.module.scss.d.ts, src/components/toggle/Toggle.tsx, src/components/toggle/__stories__/Toggle.stories.tsx
This PR allows the icon prop to work from the options on a toggle
https://amino-git-fix-toggle-zonos.vercel.app/?path=/story/amino-toggle--with-icon
=> FEAT: Allow icon on toggle

package.json, src/components/country-multi-select/CountryMultiSelectExpanded.tsx, src/components/country-multi-select/__stories__/CountryMultiSelectExpanded.stories.tsx
- [CO-730: New option for Country Multi Select Expanded](https://linear.app/zonos/issue/CO-730/new-option-for-country-multi-select-expanded)
- https://amino-git-feat-new-option-for-country-multi-select-e2848e-zonos.vercel.app/?path=/story/amino-country-multi-select-countrymultiselectexpanded--no-groups
Resolved CO-730
This PR update new option for country mutli select expanded to be able to expand by default and no group by
=> feat(CountryMultiSelectExpanded): add options to hide "Select all" checkbox and expand all groups by default

package.json, src/components/connection-map/__stories__/ConnectionMap.stories.tsx, src/components/country-multi-select/__stories__/CountryMultiSelectExpanded.stories.tsx, src/components/filter/__stories__/Filter.stories.tsx, src/components/select/__stories__/CountryMultiSelect.stories.tsx, src/components/select/__stories__/CountrySelect.stories.tsx, src/utils/hooks/useCountryOptions.tsx
This PR adds language code param for useCountryOptions
=> FEAT: useCountryOptions accepts languageCode
