package.json
src/components/Button/Button.tsx

This PR adds the ability to change the order of tabbing elements to the Button.

feat(button): add tab index

---

package.json
src/components/Card/Card.tsx

This PR allows a React node for a Card label. I thought this change was done previously, so I'm unsure of what happened to it 🤷‍♂️

feat(card): react node label

---

package.json
src/components/Select/Select.tsx

This PR adds autofocus to the Select Component.

feat(select): add autofocus

---

package.json
src/components/Select/Select.tsx

This PR prevents the Dropdown Icon from moving below the Select when the Select does not have a label.

fix(select): contain icon within select

---

package.json
src/components/Select/Select.tsx

This PR fixes the alignment of the icon which was off by a pixel.

fix(select): icon alignment

---

package.json
src/utils/AminoOnClickHandler.ts

This PR fixes the Button onClick typing to return the event.

fix(button): onClick type

---

package.json
src/components/ListItem/ListItem.tsx

This PR forwards the list item ref & adds a disabled state.

feat(list-item): add disabled & forwardRef

---

package.json
src/components/Radio/RadioGroup.tsx

This PR strongly types the radio select.

feat(radio): strongly-type

---

package.json
src/components/Radio/RadioGroup.tsx

This PR is a follow-up to #45 simplifying the type.

fix(radio): simplify callback type

---

package.json
src/components/Card/Card.tsx

This PR pulls out the onSave handler from the card & allows multiple footer actions.

feat(card): footer actions

---

package.json
src/components/Button/index.ts
src/components/Card/index.ts
src/components/Checkbox/index.ts
src/components/Combobox/index.ts
src/components/DarkModeWrapper/index.ts
src/components/Dialog/index.ts
src/components/Input/index.ts
src/components/Notice/index.ts
src/components/Radio/index.ts
src/components/Select/Select.tsx
src/components/Select/index.ts
src/components/Skeleton/index.ts
src/components/Spinner/index.ts
src/components/Tabs/Tabs.tsx
src/components/Tabs/index.ts
src/index.ts
src/utils/AminoOnSaveHandler.ts
tsconfig.json
yarn.lock

This PR reverts the previous changes upgrading all the packages. I will have to do that another time because the latest typescript caused some issues. This PR also allows us to require a select item.

refactor: revert previous changes & require select

---

package.json
src/components/Toast/ToastContext.tsx
src/stories/Toast/Toast.stories.tsx
src/stories/Toast/ToastConsumer.tsx

This PR fixes the key warning we receive from duplicate toasts.

fix(toast): key warning

---

package.json
src/components/RoundedIcon/RoundedIcon.tsx
src/stories/RoundedIcon.stories.tsx

This PR adds the ability to control the Rounded Icon background and icon color.

feat(rounded-icon): choose color

---

package.json
src/components/Layout/Layout.tsx
src/components/Layout/index.ts
src/stories/Layout.stories.tsx

This PR allows the layout to not have a header which will be helpful for the new settings design layout.

feat(layout): allow no header

---

package.json
src/components/Card/Card.tsx
src/stories/Card.stories.tsx

This PR adds footer content similar to the footer actions, just on the left instead of the right.

feat(card): add footer content

---

package.json
src/components/Card/Card.tsx
src/components/Stack/HStack.ts
src/stories/HStack.stories.tsx

This PR adds a story that helps identify an issue Cards inside of an HStack.

feat(hstack): add story

---

package.json
src/components/Button/Button.tsx
src/components/Combobox/Combobox.tsx
src/components/Input/Input.tsx
src/components/Select/Select.tsx
src/components/Slider/Slider.tsx
src/components/Slider/index.ts
src/index.ts
src/stories/Slider.stories.tsx
src/styles/theme.css
yarn.lock

Adds accessible `<Slider/>` component based on Radix-UI primitives
------------------------------------
See component demo: https://amino-ui-git-feat-scaled-slider-zonos.vercel.app/?path=/story/amino-slider--default

(feat) Add <Slider/> component

---

package.json
src/components/Layout/Layout.tsx
src/stories/Layout.stories.tsx

This PR is related to a chore [insert dashboard-web PR here] as well as the below comment found in the ```Wrapper component``` in dashboard-web: 
This PR applies increased padding to the bottom of the ```Content``` component.

fix(layout): incr content bottom padding

---

package.json
src/components/RichCheckboxGroup/RichCheckboxGroup.tsx
src/components/RichCheckboxGroup/index.tsx
src/components/RichRadio/RichRadio.tsx
src/stories/RichCheckbox.stories.tsx
yarn.lock

[Improvements to "Team member details" settings](https://myzonos.atlassian.net/browse/DM-419)
This PR was necessitated by the above Jira task. This PR introduces a ```RichCheckboxGroup``` that utilizes ```@radix-ui/react-radio-group``` ```Item``` primitive to make a similarly-styled checkbox and checkbox group. 
https://user-images.githubusercontent.com/57578761/124646116-7ca77a80-de51-11eb-8724-f7ee6414acbf.mov
Marking this as a draft until we have a resolution on [this issue](https://github.com/radix-ui/primitives/issues/770) within the @radix-ui library that I have brought up and see if we need to use the ```onMouseDown``` event handler instead of the ```onClick``` handler which seems to be having issues.

feat(rich-checkbox-group): initial commit, add story

---

package.json
src/components/Input/Input.tsx

This PR makes the Input component more flexible by allowing the value prop to be `null`.

feat(input): allow null value

---

package.json
src/components/Input/Input.tsx

This PR updates the Input callbacks to match what typescript infers from the inputs.

fix(input): onKeyPress typing

---

package.json
src/components/Radio/RadioGroup.tsx

[Sentry Issue](https://sentry.io/organizations/zonos/issues/2305355158/?project=5426364&referrer=slack)
This PR fixes an error caused by setState not happening within a hook.

fix(radio-group): infinite loop

---

package.json
src/components/Radio/Radio.tsx
src/components/Radio/RadioGroup.tsx
src/components/Radio/index.ts
src/stories/RadioGroup.stories.tsx

This PR fixes a duplicate on change call from the radio component.

fix(radio): duplicate onchange call

---

package.json
src/components/RestState/RestState.tsx
src/components/RestState/index.ts
src/index.ts
src/stories/RestState.stories.tsx

This PR creates a rest state component (add icon to text) & story for it

feat: create rest state component & story for it

---

package.json
src/components/RestState/RestState.tsx
src/components/RestState/index.ts
src/index.ts
src/stories/RestState.stories.tsx
yarn.lock

This PR merges the latest changes into master so amino.zonos.com will be updated.

Merge latest changes into master

---

package.json
src/components/RichRadio/RichRadio.tsx
yarn.lock

This PR merges the latest changes into master

Merge the latest changes into master

---

package.json
src/components/Dialog/Dialog.tsx

This PR forwards the ref from dialog content.

feat(dialog): forward content ref (#187)

---

package.json
src/components/RichRadio/RichRadio.tsx
src/stories/RichRadio.stories.tsx

This PR add property to determine which icon to use when radio is selected

feat(rich-radio): allow icon type selection

---

package.json
src/components/Layout/NavigationGroup.tsx
src/types/StyledProps.ts

This PR fixes and optimize utility StyledProps

fix(utility): styled-props

---

package.json
src/components/Collapse/Collapse.tsx
src/components/Collapse/index.ts
src/components/Layout/index.ts
src/index.ts
src/stories/Collapse/Collapse.stories.tsx

This PR adds Collapse component to amino package, adds NavigationGroup and NavigationItem component to amino package and bump version to 3.0.7

fix(layout): add layout subcomponent to package

---

package.json

This PR just bump package version to 3.0.9

bump version to 3.0.9

---

src/icons/DynamicIcon.tsx
src/index.ts
src/stories/Icons/DynamicIcon.stories.tsx
src/types/index.ts

This PR adds a new dynamic icon to Amino icons library

feat(icons): add new dynamic icons

---

package.json
src/components/Input/InputType/FloatLabelInput.tsx

This PR makes "error" attribute in float label input optional

fix(input): make "error" attr optional

---

package.json
src/components/Input/Input.tsx
src/components/Input/InputType/FloatLabelInput.tsx
src/components/RichRadio/RichRadio.tsx

This PR fixes bug of the input that re-render every time typed a word

fix(input): issue rerender every word typing

---

package.json
src/components/Select/MultiSelect.tsx
src/components/Select/Select.tsx

This PR adds a JS doc description for the value prop.

refactor(select): add jsdoc description

---

package.json
src/components/RichRadio/RichRadio.tsx
src/stories/RichRadio.stories.tsx

This PR adds optional tool tip and tooltip setting to "items" property and bumps version to 3.0.19

feat(rich-radio):optional tooltip for radio option

---

package.json
src/components/Dialog/Dialog.tsx
src/stories/Dialog.stories.tsx

This PR adds left action & updates storybook, adds a left action area, adds a long content dialog to the storybook to see gradient overflow, and adds gradient overflow styling to the dialog

Feat/dialog left action & overflow

---

src/icons/CheckMarkIcon.tsx

This PR fixes a bug with the checkbox not receiving a ref which is required for using the motion function: See `Checkbox.tsx:10`

fix(checkbox): forward ref to fix motion warning

---

.github/workflows/blank.yml

This PR updates the publish workflow to work with concurrently.

build: update node version for concurrently

---

package.json
src/hooks/useCountryOptions.tsx
src/icons/CheckMarkIcon.tsx
tsconfig.json

This PR fixes issue can't find storybook/addon module after being built.

Fix/typescript doesn't recognize types

---

package.json
src/components/Select/CountrySelect.tsx
src/components/Select/Select.tsx
src/stories/Select.stories.tsx

This PR clarifies the Select JSDocs

refactor(select): clarify jsdocs

---

package.json
src/SetupPackage.ts

This PR adds more specific to files prop in package.json

build(npm): add more specific to files props

---

.github/workflows/blank.yml
package.json

This PR remove "files" props out of package.json

build(npm):remove "files" prop out of package.json

---

package.json

This PR bumps version to 3.0.35

bump amino version to 3.0.35

---

package.json
src/components/ConfirmDialog/ConfirmDialog.tsx

This PR add "optional" to "subtitle" prop in confirm dialog and bumps version to 3.0.36

refactor(dialog):add "optional" to "subtitle" prop

---

package.json
src/types/Color.ts
src/types/ConfirmDialogOpts.ts

This PR adds optional subtitle dialog & type yellow

refactor(dialog): optional subtitle dialog & type yellow

---

package.json

This PR fixes path of setupPackage.ts

refactor: change path of setupPackage.ts

---

src/components/select/CountryMultiSelect.tsx
src/components/select/CountrySelect.tsx

This PR tries to fix building issue

refactor: only use one type of export

---

package.json

This PR print out version using to building project

build: print version before building

---

src/components/select/StyledReactSelect.tsx

This PR changes type alias to interface

refactor: change type alias to interface

---

src/types/ICountry.ts

This PR attempts to fix the build

build: avoid extending IOption

---

package.json
pull_request_template.md
src/components/select/CountryMultiSelect.tsx
src/components/select/CountrySelect.tsx
src/stories/CountrySelect/CountryMultiSelect.stories.tsx
src/stories/CountrySelect/CountrySelect.stories.tsx

This PR updates the select exports to be uniform.

refactor(select): use named export

---

package.json
src/components/button/Anchor.tsx
src/components/button/Button.tsx
src/components/input/Input.tsx
src/components/input/SearchInput.tsx
src/components/input/input-type/FloatLabelInput.tsx

This PR: 
- Bumps version to v3.0.49
- Adds props spreading parameter to Button, Anchor, Input, SearchInput, and FloatedLabelInput to accept all other attributes that are passed into those components

feat: allow to put props to interactive components

---

src/components/input/Input.tsx

fix: export InputProps

---

src/components/list/List.tsx
src/stories/List.stories.tsx

This PR adds two props to List - withBorder and withNegativeMargin to better account for dashboard styling

feat: add withBorder and withNegativeMargin props

---

package.json
src/components/alert-dialog/AlertDialog.tsx
src/components/card/Card.tsx
src/components/confirm-dialog/ConfirmDialog.tsx
src/components/cover-sheet/CoverSheet.tsx
src/components/dialog/Dialog.tsx
src/components/rest-state/RestState.tsx
src/components/section/Section.tsx
src/components/slide-over/SlideOver.tsx
src/components/text/Text.tsx
src/stories/Typography.stories.tsx
src/styles/theme.css

This PR synchronizes the new typography design to the current amino typography.

refactor(typo): sync current design typo

---

src/components/text/Text.tsx

No Jira task
This PR updates a small change of the logic to render the fontSize and lineHeight.

fix(Text):updated typography text size/lineHeight

---

package.json
src/components/input/input-type/_PasswordInput.tsx

This PR updates the icon size in passwordInput

fix(passwordInput):updated icon size

---

package.json
src/components/dialog/Dialog.tsx
src/components/input/SearchInput.tsx
src/components/notice/Notice.tsx
src/components/select/CountrySelect.tsx
src/components/select/_StyledReactSelect.tsx
src/components/styles/ColorPalette.tsx
src/components/text/Text.tsx
src/stories/RoundedIcon.stories.tsx
src/stories/Typography.stories.tsx
src/types/Color.ts
src/types/index.ts

This PR adds color to text and removes legacy colors from typescript.

feat(text): add color to text

---

package.json
src/components/notice/Notice.tsx
src/stories/Notice.stories.tsx

[FE: New UI changes to the login pages](https://myzonos.atlassian.net/jira/software/projects/CLSFY/boards/65?assignee=603058259f84a900690cdd2b&selectedIssue=CLSFY-1780)
This PR adds a functioning onClose to the Notify story in amino.

fix(notice):add functional onClose notice story

---

package.json
src/components/button/Button.tsx
src/stories/Button/Button.stories.tsx
src/styles/theme.css
src/types/Color.ts

This PR fixes the text button color and font-size.

Fix/text button color and font-size

---

package.json
src/components/section/Section.tsx

This PR updates the section margin-bottom to get closer to the designs (26px).

fix(section): margin-bottom

---

package.json
src/components/list/CollapsableList.tsx
src/stories/CollapsableList.stories.tsx

[Create List Component - Amino](https://myzonos.atlassian.net/browse/LCG-802)
This PR refactors collapsable list

refactor(collapsable-list): change prop name

---

package.json
src/components/input/input-type/_FloatLabelInput.tsx

This PR fixes a styling issue when using the Input password autofill. The div/icon background will now match the autofill color.

style(input):updated autofill input color

---

package.json
src/all.ts
src/components/badge/Badge.tsx
src/components/currency/Currency.tsx
src/components/currency/DualCurrency.tsx
src/stories/Table.stories.tsx

This PR updates the default font weight to match the designs. This PR also adds the Dual Currency Component and uses it inside the Foreign Currency Expandable Table story.

fix(badge): default font weight & add Dual Currency

---

package.json
src/components/dialog/Dialog.tsx

This PR uses default color for remove icon for the dialog

style(dialog): use default color for close-icon

---

src/components/rich-radio/RichRadio.tsx
src/stories/RichRadio.stories.tsx

This PR adds a size of 64px high - to match new Figma design. RichRadio story has been updated as well.

fix(richradio):updated size & story to match figma

---

package.json
src/components/input/Input.tsx

This PR refactors input `date` type to have target event strongly typed

refactor(dateInput):strongly type for target event

---

package.json
src/styles/amino.css

This PR imports the 'Fira Code' font-face (https://github.com/amino-ui/core/pull/325)

Import fira code fonts

---

package.json
src/components/input/Input.tsx
src/components/input/input-type/_TimeInput.tsx
src/stories/Input.stories.tsx

[Time Input - Amino Component](https://myzonos.atlassian.net/browse/LCG-898)
This PR adds time input component

feat: add time input component

---

build-utils/css/constants/theme.ts
build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap
package.json
src/components/file-upload/FileUpload.tsx
src/stories/FileUpload.stories.tsx
src/styles/constants/theme.ts

This PR:
- Refactors the file upload component to have `onRemove` and `uploadedFiles` to be optional
- Add `@deprecated` to some variables in `theme.ts`

refactor(file-upload):: make onRemove and uploadedFiles be optional

---

src/utils/__tests__/truncateText.test.ts
src/utils/truncateText.ts

This PR updates the `testTruncate` test to use the actual types for the function parameters.

test(truncateText): test against typed params

---

src/utils/__tests__/truncateText.test.ts
src/utils/truncateText.ts
yarn.lock

[FE: Clean up bulk classify review page, including formatting the preview and moving the "Add countries" button](https://myzonos.atlassian.net/jira/software/projects/CLSFY/boards/65?assignee=603058259f84a900690cdd2b&selectedIssue=CLSFY-1872)
This PR gives additional options to truncate characters and/or white space for URL's, etc. Added tests for truncateText.

fix(text):additional options for truncateText

---

package.json

Don't open chrome by default now.

build: change npm scripts to use default browser and not open by default

---

package.json

This PR fixes the build fail for (https://github.com/amino-ui/core/pull/336)

Bump version 3.2.4

---

package.json
src/components/select/_StyledReactSelect.tsx

Error state on Select will outline in red, like other inputs.

feat: select error state red outline

---

package.json

Adding tag to the last code update.

Patch: Vstack v 3.2.18

---

package.json

Forgot to bump version on #355  😢

Bump version 3.2.20

---

.github/workflows/release.yml
package.json

This PR makes it easier to find out what changed by automatically generating release notes for each tag. 
This PR also stops publishing to NPM when pushing to master. A library functions differently from a Web App and this behavior wasn't something we ever used.

build: auto-release

---

.github/workflows/publish.yml
.github/workflows/release.yml

This PR fixes our auto-generated release notes.

fix: auto-generate release notes

---

.github/workflows/release.yml
package.json
src/components/section/_SectionInnerWrapper.tsx

This PR moves actions box same line as the title.

refactor: move actions box same line as title

---

.github/workflows/release.yml

Will allow manual triggers of the release workflow. Go to Actions > All Workflows > Release > Run workflow.

build(gh-actions): manual release trigger option

---

package.json
src/components/toast/Toast.tsx
src/components/toast/ToastContext.tsx
src/stories/Toast/ToastConsumer.tsx

This PR adds an optional prop to toasts (notify) for the delay before dismissing it.

feat: toast duration prop

---

package.json
src/components/select/_StyledReactSelect.tsx
src/stories/Select.stories.tsx

This PR fixes an issue where select inputs would have fixed position by default when scrolling, which lead to jarring visuals.
Demo: https://amino-ui-git-fix-scrollable-select-zonos.vercel.app/?path=/story/amino-select--scrollable-select

story: scrollable select

---

package.json
src/components/currency/Currency.tsx
src/components/currency/DualCurrency.tsx

[Enhanced landed cost breakdown for GraphQL users](https://myzonos.atlassian.net/browse/EC-244)
As part of the task above, we have a new format for currency.   
New format: SYMBOL PRICE ISO_CURRENCY_CODE. 
Example: $10 USD, $10 AUD, €10 EUR. 
This PR will update style and apply new format for currency component

refactor(currency): new format

---

package.json
src/components/table/TableRow.tsx
src/components/table/TableRowCollapse.tsx

This PR add event type for onClick action in TableRow and TableRowCollapse

refactor: change event type for table row

---

.github/workflows/publish.yml

This PR change branch name on publish yml

build: change branch name

---

package.json
src/components/list/CollapsibleList.tsx
src/components/table/TableRowCollapse.tsx

This PR makes all the collapse icons rotate the same way (counter clockwise)

misc: make all collapse icon transitions go counter clockwise

---

package.json
src/components/card/Card.tsx
src/components/card/__stories__/Card.stories.tsx
src/components/table/TableRow.tsx

This PR updates the `TableRow` component to now have a gray background on hover. It also adds a spacing prop to the `Card` component.

Feat: Table hover and card spacing

---

package.json
src/all.ts
src/utils/getFuzzySearch.ts
yarn.lock

This PR adds `fuse` to amino as our frontend fuzzy searching library.

feat(search): add fuzzy search

---

package.json
src/__stories__/Ripple.stories.tsx
src/components/button/RippleGroup.tsx
src/components/button/_Ripple.tsx

This PR fixes an issue with the Ripple not cleaning up timeouts. I restructured it to fix this issue. Also made the delay prop affect the CSS transition so it looks better.

fix: ripple timeout leak

---

src/components/currency/DualCurrency.tsx

No Jira task
This PR adds a className to `DualCurrency` - needed for styling to render properly in dashboard.
Only want to pass down className to the DualCurrencyWrapper if it's a DualCurrency.

added className prop to DualCurrency

---

package.json

No Jira task
This PR bumps the version up from previous pull request (https://github.com/amino-ui/core/pull/459)

Bump version 3.4.49

---

package.json

This PR moves the repo over to the Zonos org.

refactor: move repo to zonos org

---

package.json

This PR updates the package name, so we are publishing in the correct spot.

build(amino): update name

---

README.md

This PR updates the badge on the README.

misc: updated npm version badge in README

---

src/components/graph-matrix/GraphMatrix.tsx
src/components/nested-data-table/NestedDataTable.tsx
src/components/nested-data-table/NestedDataTableHasura.tsx

This PR de-couple the nested data table so it would be flexibly consumable

refactor: decouple the nested data table

---

package.json

This PR bumps the version and publish to npm for this PR https://github.com/Zonos/amino/pull/472

Bump version 4.1.6

---

package.json
src/components/list-item/ListItem.tsx

[Remove deprecations task](https://myzonos.atlassian.net/jira/software/projects/FE/boards/145?assignee=61f46737138863006acc2c37&selectedIssue=FE-223)
This PR removes 2 deprecated props from the `ListItem` component.

FE-223 Fix: Remove deprecated props from ListItem component

---

package.json

This PR bumps the version for this previous PR: #478

Bump version 4.2.2

---

package.json
src/components/mdx-code-block/MdxCodeBlock.tsx
src/components/mdx-code-block/__stories__/MdxCodeBlock.stories.tsx

This PR adds a max height to the code block prop

feat: mdx code block max height prop

---

package.json
src/all.ts
src/components/mdx-bread-crumbs/MdxBreadCrumbs.tsx
src/components/mdx-card/MdxCard.tsx
src/components/mdx-hero/MdxHero.tsx
src/components/mdx-hero/__stories__/MdxHero.stories.tsx

[Amino theme updates](https://myzonos.atlassian.net/jira/software/projects/FE/boards/145?assignee=61f46737138863006acc2c37&selectedIssue=FE-232)
This PR adds the Hero component and fixes the breadcrumbs and card components to be consumed by MDX.

FE-232: Added MdxHero and made edits to breadcrumbs and MdxCard

---

package.json
src/components/graph-matrix/GraphMatrix.tsx

This PR fixes the graphiql explorer tab sizing issues.

fix: graphiql explorer tab sizing

---

build-utils/css/constants/theme/day/colors/_transparent.ts
build-utils/css/constants/theme/night/colors/_transparent.ts
build-utils/css/utils/__tests__/__previous-test-files__/night-theme.css
build-utils/css/utils/__tests__/__previous-test-files__/theme.css
build-utils/css/utils/__tests__/__snapshots__/convertToCssVariable.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateCSS.test.ts.snap
package.json
src/components/mdx/mdx-image/MdxImage.tsx
src/components/textarea/Textarea.tsx
src/components/textarea/__stories__/Textarea.stories.tsx
src/components/theme-select/ThemeSelect.tsx
src/styles/constants/theme.ts
src/styles/theme.css

[Theme fixes](https://myzonos.atlassian.net/jira/software/projects/FE/boards/145?selectedIssue=FE-270)
This PR adjusts the following components/styles:
- Black transparency: uses the same hex as gray0
- Textarea: shows the placeholder now
- MdxImage: uses the shadow prop for CSS instead of an extra element
- ThemeSelect: background color fixed for toggle

Fix(theme): Minor color changes and bug fixes

---

build-utils/css/constants/theme.ts
build-utils/css/utils/__tests__/__previous-test-files__/theme.css
build-utils/css/utils/__tests__/__snapshots__/convertToCssVariable.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateCSS.test.ts.snap
package.json
src/components/button/Button.tsx
src/components/layout/Layout.tsx
src/components/layout/NavigationGroup.tsx
src/styles/constants/theme.ts
src/styles/theme.css

[EC-1685 - Redesign Sidebar](https://myzonos.atlassian.net/browse/EC-1685)
This PR adjusts some styles for the new Dashboard sidebar redesign

Dashboard sidebar changes

---

README.md

This PR makes the version badge link directly to npm instead of going through a slow redirect.

misc: readme badge direct link to npm

---

package.json
src/__stories__/Storage.stories.tsx
src/types/Theme.ts
src/utils/__tests__/storage.test.ts
src/utils/hooks/useAminoTheme.ts
src/utils/storage.ts

This PR fixes the subtle issue causing screen flashes due to SWR cache not being populated/ready on initial render when using the theme hook.

fix: theme initial load with swr

---

package.json
src/utils/hooks/useAminoTheme.ts

This PR fixes the local storage usage to be client side only.
I linked locally and tested now, so this one should work

fix: client side localstorage

---

package.json
src/components/button/Button.tsx

This PR adds a prop for custom hover color for special situations. May need to add a hoverColor prop for text color later, but not needed for what I'm doing.

Feat: hoverBackground prop for buttons

---

package.json
src/components/layout/Layout.tsx

This PR changes the layout content body to have 24px of padding all around. This matches latest designs.

Fix: layout padding

---

package.json
src/components/layout/NavigationGroup.tsx

This PR changes the StyledNavigationItem height from 36px to 32px to align with design

fix: NavItem height

---

package.json
src/components/layout/NavigationGroup.tsx

This PR adjust the NavigationItem styles to match design

fix: adjust style to match design

---

.eslintrc.js
package.json
pnpm-lock.yaml
src/utils/hooks/__tests__/useStorage.test.ts
src/utils/hooks/useStorage.ts
src/utils/storage.ts

This PR fixes the useStorage hook so it works properly and adds tests.

fix: useStorage hook and tests

---

build-utils/css/constants/theme/_variablesUsingColors.ts
build-utils/css/utils/__tests__/__previous-test-files__/night-theme.css
build-utils/css/utils/__tests__/__previous-test-files__/theme.css
build-utils/css/utils/__tests__/__snapshots__/convertToCssVariable.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateCSS.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateColorConstantFromSvgs.test.ts.snap
src/components/confirm-dialog/ConfirmDialog.tsx
src/styles/constants/theme.ts
src/styles/theme.css

[FE-439 - [POWER RANKING] - Catalog design review fixes: Main page](https://myzonos.atlassian.net/browse/FE-439)
This PR updates the icons on the ConfirmDialog component to match Amino 2.0 design.
This is to facilitate the design requirements of the GraphQL catalog

fix: update ConfirmDialog icons to Amino 2.0

---

package.json
src/components/drop-zone/DropZone.tsx

the effective drop zone for files was the middle of the DropZone UI.
This increases that so anywhere within the dotted border can be dropped.
[FE-443 - [POWER RANKING] - Catalog design review fixes: Import dialogue](https://myzonos.atlassian.net/browse/FE-443)
This PR fixes the following:
the effective drop zone for files was the middle of the DropZone UI.
This increases that so anywhere within the dotted border can be dropped.

fix: increase effective DropZone size

---

package.json
src/components/input/Input.tsx
src/components/input/__stories__/Input.stories.tsx

This PR fixes the number input suffix prop to accept null to disable it. Also fixes the story prop names.

fix: number input suffix null option

---

src/components/toast/Toast.tsx
src/components/toast/ToastContext.tsx
src/components/toast/__stories__/ToastConsumer.tsx
src/types/Color.ts

[FE392 - Classify: Amino: Error toast alignment](https://myzonos.atlassian.net/browse/FE-392)
This PR does the following: 
add ability to determine what direction the toast animates in from:
- left, right, top, bottom
add ability to determine where the toast appears on the page.
Usage:
- `const notify = useNotify()`
- `notify(<toast message>, {direction, duration, intent}, {bottom?: <string>, left?: <string>})`
- `{bottom, left}` location object is separate and optional to not muddy up the `Toast` component
- location object only used by `ToastContext` so don't want to pass in `props` object
updated stories accordingly
- add Direction, Horizontal Offset, Vertical Offset to Custom Toast panel

feat: customized toast positioning

---

package.json

This PR bumps the version that was missed in my previous toast PR

Bump version 5.1.6

---

package.json
src/icons/icon-base/_IconBase.tsx
src/types/IconProps.ts
src/utils/getProductDetails.tsx

This PR updates the icon prop descriptions to say the default for size.

misc: icon props described as 24 by default

---

package.json
src/components/badge/Badge.tsx
src/components/tag/Tag.tsx

Adjusts the styling for the tags and badges components to match Figma

updated styling on tags and badges

---

package.json
src/components/alert-dialog/AlertDialog.tsx
src/components/alert-dialog/__stories__/AlertConsumer.tsx
src/components/confirm-dialog/ConfirmDialog.tsx
src/components/confirm-dialog/__stories__/ConfirmConsumer.tsx
src/components/cover-sheet/CoverSheet.tsx
src/components/cover-sheet/CoverSheetActions.tsx
src/components/cover-sheet/__stories__/CoverSheet.stories.tsx
src/components/dialog/Dialog.tsx
src/components/dialog/__stories__/Dialog.stories.tsx
src/components/text/Text.tsx

Updates the buttons and text styling for the cover sheet to match the updated design.
Updates the buttons and styling of all dialogs and alerts to use the new buttons.
Updates the font weight for the Title(XL) size to match designs.

Updated cover sheet and dialogs

---

package.json
src/components/banner/Banner.tsx
src/components/rich-radio/RichRadio.tsx
src/components/thumbnail/Thumbnail.tsx

Updates to duotone tone icon colors on the thumbnail and banner components.
Updated the sizing of the checkbox "duotone" icon on the rich radio.

Duotone updates

---

package.json
src/components/dialog/Dialog.tsx
src/components/filter/__stories__/Filter.stories.tsx
src/components/filter/filter-amount/FilterAmount.tsx
src/components/filter/filter-amount/filterAmountReducer.ts
src/components/filter/filter-date/DateControls.tsx
src/components/filter/filter-date/FilterDate.tsx
src/components/filter/filter-date/filterDateReducer.ts
src/components/filter/filter-multi-select/FilterMultiSelect.tsx
src/components/filter/filter-select/FilterSelect.tsx
src/components/filter/filter-text/FilterText.tsx
src/components/filter/useFilterWrapper.tsx
src/components/slide-over/SlideOver.tsx
src/components/slide-over/__stories__/SlideOver.stories.tsx

This PR updates the `SlideOver`. 
Also:
- Refactors the Filters to be more consistent and easier to work with
- Removes the commented out dialog gradient that has been there forever.
- Removes the last Figma references to the old Amino Stickers (SlideOver was the last one)
Cade: fix switch color.

feat(SlideOver): update designs

---

build-utils/css/constants/theme.ts
build-utils/css/utils/__tests__/__previous-test-files__/theme.css
build-utils/css/utils/__tests__/__snapshots__/convertToCssVariable.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateCSS.test.ts.snap
package.json
src/components/simple-table/SimpleTable.tsx
src/components/switch/Switch.tsx
src/styles/constants/theme.ts
src/styles/theme.css

This PR fixes my previous PR for the switch. The night mode background color was wrong for the normal switch. It also fixes a visibility transition for the switch.

fix(switch): night background color on switch

---

package.json
src/components/select/_StyledReactSelect.tsx

Updates the tags on the multi-select component

multi-select tag update

---

package.json
src/components/simple-table/SimpleTable.tsx
src/components/simple-table/__stories__/SimpleTable.stories.tsx
src/components/slide-over/SlideOver.tsx
src/components/slide-over/__stories__/SlideOver.stories.tsx

This PR:
- fixes the slide over to use the width prop correctly in the transition.
- Refactors `SimpleTable` with `isRowChecked` for more custom selectable rows. (allows a use case that existed with custom checkboxes)

fix some components

---

package.json
src/components/checkbox/Checkbox.tsx
src/components/simple-table/SimpleTable.tsx
src/components/simple-table/__stories__/SimpleTable.stories.tsx
src/components/slide-over/__stories__/SlideOver.stories.tsx

This PR improves the simple table to match existing use cases better.
Now when checkboxes are already selected, on row click becomes the checkbox event.

feat(SimpleTable): fix checkbox clicking and make props consistent

---

package.json
src/components/toast/Toast.tsx

Visual updates to the toast component

updated toasts

---

package.json
src/components/connection-map/ConnectionMap.tsx

Updates the connection map to match designs.

map updates

---

package.json
src/components/filter/useFilterWrapper.tsx

Quick fix to update the filter icon size that was missed last PR
Minor styling updates as well to the icons

update filter icons

---

.eslintrc.js
package.json
src/components/button/RippleGroup.tsx
src/components/button/useRipple.ts
src/components/layout/__stories__/UserMenu.tsx
src/components/list-item/ListItem.tsx
src/components/select/CountryMultiSelect.tsx
src/components/select/CountryPhoneSelect.tsx
src/components/select/MultiSelect.tsx
src/components/select/Select.tsx
src/components/select/_StyledReactSelect.tsx
src/components/sortable-list/SortableList.tsx
src/components/sortable-list/SortableListItem.tsx
src/components/sortable-list/__stories__/SortableList.stories.tsx
src/components/stack/Stack.tsx
src/components/styles/__stories__/BoxShadow.stories.tsx
src/components/tag/Tag.tsx
src/types/BaseProps.ts
src/types/Country.ts
src/types/FetcherError.ts
src/types/JsonError.ts
src/types/SwrtParams.ts
src/types/ts-reset/common.d.ts
src/types/ts-reset/fetch.d.ts

This PR adds the "type over interface" rule.

Fix(types): Added type over interface rule

---

package.json
src/components/input/Input.tsx
src/components/input/input-type/_DateInput.tsx
src/components/input/input-type/_FloatLabelInput.tsx
src/components/select/_StyledReactSelect.tsx
src/components/textarea/Textarea.tsx

Updated text fields and selects to have a variable border radius based on the input size.

Updates to input border radius based on size

---

package.json
src/components/checkbox/Checkbox.tsx
src/components/select/_StyledReactSelect.tsx
src/components/select/__stories__/MultiSelect.stories.tsx

This PR fixes the checkbox in the `Select`.

fix(checkbox): select propagation

---

package.json
src/components/button/MenuButton.tsx
src/components/menu/MenuItem.tsx

Updates the menu button styling
Fixes the dark mode hover not showing

menu button menu updates

---

package.json
src/components/banner/Banner.tsx
src/components/banner/__stories__/Banner.stories.tsx
src/components/button/Button.tsx

This PR fixes the Banner spacing between the actions and title in the header. Also adds hover styling to the buttons in banners.

fix(Banner): spacing

---

package.json
src/components/button/Button.tsx
src/components/button/__stories__/Button.stories.tsx

This PR fixes a styling issue in the `Button` loading state where the content was transparent.
Before:

fix(Button): loading state

---

package.json
src/components/button/Button.tsx
src/components/cover-sheet/CoverSheet.tsx
src/components/cover-sheet/__stories__/CoverSheet.stories.tsx
src/components/layout/Layout.tsx
src/components/simple-table/SimpleTable.tsx

https://myzonos.atlassian.net/browse/FE-676
This PR tweaks some styling to match designs.

fix: design consistency

---

build-utils/css/constants/theme/day/_shadow.ts
build-utils/css/constants/theme/night/_shadow.ts
build-utils/css/utils/__tests__/__previous-test-files__/night-theme.css
build-utils/css/utils/__tests__/__previous-test-files__/theme.css
build-utils/css/utils/__tests__/__snapshots__/convertToCssVariable.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateCSS.test.ts.snap
package.json
src/components/button/Button.tsx
src/styles/constants/theme.ts
src/styles/theme.css

Updates to the primary buttons disabled states to be more obivous. 
Added a "disabled button shadow" for the new disabled states.

Updated primary buttons disabled state

---

package.json
src/components/switch/Switch.tsx

https://myzonos.atlassian.net/browse/FE-675
This PR adjusts the selector for the theme select to be better.

fix(ThemeSelect): styling priority

---

package.json
src/components/layout/Layout.module.scss

- Remove test color when testing css module
This PR: remove the test red color on layout component

Fe 710 research on the css module

---

package.json
src/components/card/Card.module.scss
src/components/card/Card.module.scss.d.ts
src/components/card/Card.tsx
src/components/layout/Layout.module.scss
src/components/layout/Layout.tsx
src/types/ts-reset/scss-modules.d.ts

[FE-734 - Convert `Card` to Css modules in Amino](https://myzonos.atlassian.net/browse/FE-734)
This PR converts the `Card` component to use CSS modules instead of Styled Components

refactor(Card): css modules

---

package.json
src/components/dialog/BaseDialog.tsx

This PR fixes a bug where the className was applied to the dialog backdrop rather than the popup

fix(basedialog): move className to popup

---

package.json
src/components/checkbox/Checkbox.tsx
src/components/checkbox/__stories__/Checkbox.spec.ts

This PR adds back a checkbox class.

fix: checkbox class

---

package.json
src/components/simple-table/SimpleTable.tsx
src/components/simple-table/__stories__/SimpleTable.stories.tsx

This PR fixes `SimpleTable` link rows that are selectable.

fix(SimpleTable): links with selectability

---

README.md
package.json
src/components/filter/FilterWrapper.tsx
src/components/filter/__stories__/Filter.stories.module.scss
src/components/filter/__stories__/Filter.stories.module.scss.d.ts
src/components/filter/__stories__/Filter.stories.tsx
src/components/filter/useFilterWrapper.tsx

This PR fixes the filter ref error.

fix(Filter): ref warning

---

package.json
src/components/simple-table/SimpleTable.tsx

This PR fixes a small issue with adding keys in the wrong spot in `SimpleTable`

fix(SimpleTable): header keys

---

package.json
src/components/filter/__stories__/Filter.stories.tsx
src/components/filter/filter-select/FilterSelect.tsx

[Order detail page updates](https://myzonos.atlassian.net/browse/IP-329)
This PR adds the selected text truncation to the Filter Select.

feat(filter): add selected text truncation

---

package.json
src/components/checkbox/Checkbox.tsx

Related to [FE-810 - Dashboard to css modules](https://myzonos.atlassian.net/browse/FE-810)
This PR adds a `'disabled'` string to a disabled checkbox classList becuase tests in Dashboard depend on it

fix: checkbox className

---

package.json
src/components/section/_SectionHeader.module.scss
src/components/section/_SectionInnerWrapper.module.scss

This PR fixes the VSection actions styling

fix(VSection): ensure the action buttons are separated from label

---

package.json
src/components/simple-table/SimpleTable.module.scss
src/components/simple-table/SimpleTable.module.scss.d.ts
src/components/tooltip/Tooltip.module.scss
src/components/tooltip/Tooltip.module.scss.d.ts
src/components/tooltip/Tooltip.tsx

This PR fixes more small bugs that were found in Amino components
- SimpleTable
- add `:global()` to the extra css classes
- Tooltip
- fix text color
[https://bugs.amino.zonos.com](https://bugs.amino.zonos.com)

fix: more small bugs found

---

package.json
src/components/country-multi-select/CountryMultiSelectExpanded.module.scss
src/components/country-multi-select/CountryMultiSelectExpanded.tsx

feat: max height prop in country multi select

---

build-utils/css/constants/theme/_variablesUsingColors.ts
build-utils/css/utils/__tests__/__previous-test-files__/night-theme.css
build-utils/css/utils/__tests__/__previous-test-files__/theme.css
build-utils/css/utils/__tests__/__snapshots__/convertToCssVariable.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateCSS.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateColorConstantFromSvgs.test.ts.snap
package.json
src/components/cover-sheet/CoverSheet.module.scss
src/components/cover-sheet/CoverSheet.tsx
src/components/layout/Layout.module.scss
src/components/layout/NavigationGroup.module.scss
src/components/layout/NavigationGroup.module.scss.d.ts
src/components/layout/NavigationGroup.tsx
src/components/menu/Menu.module.scss
src/components/rich-checkbox/RichCheckbox.module.scss
src/components/rich-radio/RichRadio.module.scss
src/components/rich-radio/RichRadio.tsx
src/components/slide-over/SlideOver.module.scss
src/components/table/TableCell.tsx
src/components/toggle/Toggle.module.scss
src/styles/constants/theme.ts
src/styles/theme.css
src/styles/theme.scss

Adjusted the sizing for the navigation menu items.
Updated styling for borders on multiple components. 
Other small subtle tweaks.

Adjusted styling for menu items and border colors

---

package.json
src/components/button/MenuButton.module.scss
src/components/filter/__stories__/Filter.stories.module.scss
src/components/simple-table/SimpleTable.module.scss
src/components/tabs/Tabs.module.scss

Fixed the menu for the menu button being the wrong color (my bad) and adjusted other borders I I missed earlier.

fixed the dialog on the menu button and adjusted other borders

---

package.json
src/components/dialog/BaseDialog.tsx

[Test Logout functionality - authorization.](https://linear.app/zonos/issue/FE-763/test-logout-functionality-authorization)
This PR allows us to use a custom root selector to pop a dialog from.
This change was for the label integration extension

feat(dialog): add root selector

---

build-utils/css/constants/theme/day/colors/_oneOffColors.ts
build-utils/css/constants/theme/night/colors/_oneOffColors.ts
build-utils/css/utils/__tests__/__previous-test-files__/night-theme.css
build-utils/css/utils/__tests__/__previous-test-files__/theme.css
build-utils/css/utils/__tests__/__snapshots__/convertToCssVariable.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateAminoConstants.test.ts.snap
build-utils/css/utils/__tests__/__snapshots__/generateCSS.test.ts.snap
package.json
src/styles/constants/theme.ts
src/styles/theme.css
src/styles/theme.scss

Changed backdrop color and added new color variable

Adjusted colors and added new color variable

---

package.json
src/components/simple-table/SimpleTable.module.scss
src/components/tabs/Tabs.module.scss
src/components/text-avatar/TextAvatar.module.scss
src/components/text-avatar/TextAvatar.tsx

Adjusts padding and height of table headers
Adjusts the text avatars
Fixes tabs to have blue text color when selected

minor style fixes to tables, text avatars, and tabs

---

package.json
src/components/flex/Flex.module.scss
src/components/flex/Flex.tsx

This PR brings feature parity to the Amino Flex from the dashboard Flex component

Fix: Added missing props to Flex

---

package.json
src/components/filter/filter-amount/FilterAmount.tsx

This PR fixes the amount filter logic.
I have decided to leave the `useStateUrl` code because it is helpful for testing the filters with state derived from outside the component, even though that code won't be used.

fix: amount filter logic

---

package.json
src/components/dialog/DismissableDialog.tsx
src/components/dialog/alert/AlertContext.tsx
src/components/dialog/confirm/ConfirmContext.tsx
src/components/dialog/confirm/__stories__/ConfirmConsumer.tsx
src/components/simple-table/SimpleTable.module.scss

This PR adds a width prop to alert/confirm.

feat: add width option to alert/confirm

---

package.json
src/components/button/Button.module.scss
src/components/filter/FilterWrapper.module.scss
src/components/rich-card-select/RichCardStateSelect.module.scss
src/components/rich-checkbox/RichCheckbox.module.scss
src/components/rich-radio/RichRadio.module.scss
src/components/tabs/Tabs.module.scss

Adjusts the contrast on the link buttons and text based on some feedback, particularly in dark mode.

Blue text contrast update

---

package.json
src/components/input/MultiInput.tsx
src/components/text-avatar/TextAvatar.tsx

This PR removes a hard coded placeholder. It also adds className and style to TextAvatar.

Fix: MultiInput and TextAvatar

---

package.json
src/components/button/MenuButton.tsx
src/components/checkbox/Checkbox.module.scss
src/components/checkbox/Checkbox.module.scss.d.ts
src/components/checkbox/Checkbox.tsx
src/components/checkbox/__stories__/Checkbox.stories.tsx
src/components/simple-table/SimpleTable.tsx
src/components/simple-table/__stories__/SimpleTable.stories.tsx

This PR fixes the checkboxes and menu buttons inside the table.

fix: checkbox in table

---

package.json
src/components/slide-over/SlideOver.module.scss

This PR fixes the height of the slideover so it doesn't go off screen. The margin is considered in height calculation.

fix(slideover): fix height of slideover

---

package.json
src/all.ts
src/components/input/MultiInput.tsx
src/components/textarea/Textarea.module.scss
src/components/textarea/Textarea.module.scss.d.ts
src/components/textarea/Textarea.tsx
src/components/textarea/__stories__/Textarea.stories.tsx
src/styles/reset.css
src/utils/hooks/useHeightAdjustTextarea.ts
src/utils/multiinput/__tests__/parseStringIntoTags.test.ts
src/utils/multiinput/parseStringIntoTags.ts

<https://amino-git-fix-components-zonos.vercel.app/?path=%2Fdocs%2Famino-textarea--docs>
This PR changes the textarea to:
- Expand with the text by default
- Removes the resize icon in the textarea
- Shifts the actions to be relative below the textarea
This PR changes the multiinput to:
- Parse pasted content into tags
- Wrote tests to verify the parsing

FIX: Textarea and Multiinput

---

package.json
src/components/textarea/Textarea.module.scss
src/components/textarea/Textarea.module.scss.d.ts
src/components/textarea/Textarea.tsx
src/styles/reset.css

This PR fixes the textarea spacing when there are actions. It did not look very good in production. (10em was the original value before my last PR for textareas without actions)

FIX: textarea spacing

---

package.json
src/components/select/MultiSelect.tsx
src/components/select/Select.tsx
src/components/select/_StyledReactSelect.tsx

This PR actually fixes the select props, I pulled into dashboard and it checked out....

SELECT PROPS ALLOW NULL FOR REAL

---

.github/workflows/publish.yml

chore: update Node.js version and change build command in CI workflow

---

.github/workflows/playwright.yml

This PR changes playwright workflow to use microsoft container for playwright and use ubuntu os instead of macos

refactor: update playwright workflow to use microsoft container and use ubuntu os instead of macos

---

package.json

This PR upgrades the peer dependencies for React to 18 or 19.

FIX: Peer dependencies for React

---

package.json
src/components/input/input-simple/input-type/_InputBase.module.scss
src/components/select/_StyledReactSelect.module.scss
src/components/select/_StyledReactSelect.module.scss.d.ts
src/components/select/_StyledReactSelect.tsx

Fixes the extra bottom margin on select inputs to only be for the label and adds weight to input prefix and suffix.

Quick fix for extra margin on selects

---

package.json
src/all.ts
src/components/country-multi-select/CountryMultiSelectExpanded.module.scss
src/components/country-multi-select/CountryMultiSelectExpanded.tsx
src/components/country-multi-select/CountryMultiSelectExpandedOption.tsx
src/components/country-multi-select/__stories__/CountryMultiSelectExpanded.stories.tsx
src/components/radio/RadioGroup.module.scss
src/icons/flag-icon/FlagIcon.tsx
src/utils/style.ts

https://thien.amino.zonos.com/?path=/story/amino-country-multi-select-countrymultiselectexpanded--no-groups-fixed-height
https://thien.amino.zonos.com/?path=/story/amino-country-multi-select-countrymultiselectexpanded--no-groups-with-disabled-tooltip
This PR enhance component with new height prop and tooltip support for disabled countries

feat(CountryMultiSelectExpanded): enhance component with new height prop and tooltip support for disabled countries

---

package.json
src/components/toggle/Toggle.module.scss
src/components/toggle/Toggle.module.scss.d.ts
src/components/toggle/Toggle.tsx
src/components/toggle/__stories__/Toggle.stories.tsx

<https://nick.amino.zonos.com/?path=/story/amino-toggle--disabled>
This PR adds a disabled state to the Toggle component.

feat(Toggle): add disabled state functionality and update styles
